[package]
name = "flux-api"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration"]

[dependencies]
axum = { version = "^0.6", features = ["headers"] }
dotenv = "0.15.0"
fake = "2.6.1"
jsonwebtoken = "8.3.0"
sea-orm = { version = "^0.12", features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
  "macros",
  "with-uuid",
  "with-time",
] }
serde = { version = "^1.0", features = ["derive"] }
tokio = { version = "^1.31", features = ["full"] }
validator = { version = "0.16.1", features = ["derive"] }
uuid = { version = "1.4.1", features = ["v4", "v7"] }

migration = { path = "./migration" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["json"] }
chrono = "^0.4"

# [build]
# rustflags = ["--cfg", "uuid_unstable"]

# [dev-dependencies]
# tower = { version = "0.4.13", features = ["util"] }
