[package]
name = "flux-api"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration"]

[dependencies]
axum = "0.7.2"
dotenv = "0.15.0"
jsonwebtoken = "9.2.0"
sea-orm = { version = "0.12.8", features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
  "macros",
  "with-uuid",
  "with-time",
  "with-json",
] }
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }
validator = { version = "0.16.1", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4", "v7"] }

migration = { path = "./migration" }
tracing = "0.1.40"
chrono = "0.4.31"
webauthn-rs = { version = "0.4.8", features = [
  "danger-allow-state-serialisation",
] }
rand = { version = "0.8.5", features = ["min_const_gen"] }
serde_json = "1.0.108"
itertools = "0.12.0"
reqwest = { version = "0.11.22", features = ["json"] }
tokio-stream = "0.1.14"
async-nats = "0.33.0"
axum-extra = { version = "0.9.0", features = ["typed-header"] }
tracing-opentelemetry = "0.22.0"
opentelemetry = { version = "0.21.0", features = ["logs", "metrics", "trace"] }
opentelemetry_sdk = { version = "0.21.1", features = [
  "rt-tokio",
  "logs_level_enabled",
] }
opentelemetry-otlp = { version = "0.14.0", features = [
  "logs",
  "metrics",
  "trace",
] }
tracing-subscriber = "0.3.18"
opentelemetry-appender-tracing = "0.2.0"

# [build]
# rustflags = ["--cfg", "uuid_unstable"]

# [dev-dependencies]
# tower = { version = "0.4.13", features = ["util"] }
