[package]
name = "flux-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.0-rc.2", features = ["headers"] }
dotenv = "0.15.0"
fake = "2.5.0"
jsonwebtoken = "8.1.1"
sea-orm = { version = "0.9.3", features = [
  "sqlx-postgres",
  "runtime-tokio-native-tls",
  "macros",
  "with-uuid",
  "with-time",
] }
serde = { version = "1.0.145", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
validator = { version = "0.16.0", features = ["derive"] }

[dev-dependencies]
tower = { version = "0.4.13", features = ["util"] }
migration = { path = "./migration" }
