[package]
name = "flux-api"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration"]

[dependencies]
axum = { version = "0.6.12", features = ["headers"] }
dotenv = "0.15.0"
fake = "2.5.0"
jsonwebtoken = "8.3.0"
sea-orm = { version = "0.11.2", features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
  "macros",
  "with-uuid",
  "with-time",
] }
serde = { version = "1.0.159", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
validator = { version = "0.16.0", features = ["derive"] }
uuid = { version = "1.3.0", features = ["v4", "v7"] }

migration = { path = "./migration" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }
chrono = "0.4.24"
tokio-cron-scheduler = "0.9.4"

# [build]
# rustflags = ["--cfg", "uuid_unstable"]

# [dev-dependencies]
# tower = { version = "0.4.13", features = ["util"] }
