services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    command: "cargo watch -x run"
    environment:
      APP_ADDR: 0.0.0.0:3000
      DATABASE_URL: postgres://postgres:postgres@flux-pg.flux.local/flux
      HISTFILE: /app/.local/.bash_history
      AUTH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpQIBAAKCAQEAnh9vfU9CB6xDJBYUc+5RaCKdTiK0JKab/3CSgffzbfOFLTLl\nFpjdfL+9KQKUE+tvEL4MNW0CYeND25Gueycp7of2+Xn8ec2N6ah/EY4t+dUHeRS6\nLEUXVkOfQglL9hhVQG7N5lBFntlHxXnWOCli4arNpDdKMRVjy52G9aQbUIn3gx09\nKglre0dS1M4LORXnlFReblFK0V342LuTD9oamzpuJw4Gpj7WwXe+obLwDHIoBK1T\nBdJF+AQHPbaT8nAZBdAzOx8zTObd0bHfUuHbD8IzwY2V/OwPzNhJC2N8uznhJp8g\nBjqr206Y4D9Y3n62TqStk4gjNpMFBqmckBASkQIDAQABAoIBAQCVe5pmmHsPzeZb\nQxRq1K3ZCIA10dEDpQ5s2ftnKwTSuRj5tdelGTaqLImjL3DVtAj3hvL7vuY1rCgG\ndx7ABjI58gelqZDphU3Xyxb1fbgxKxc5fELUfyykvKDeSPOq3y4ZD6dPSCvJFBgp\ntBi0V0vHkzV9PVfCNzp0z6M6rb200HzYJ6AwGVdb4YN5r7VvldxLzsgLg6Eie9vA\n7etbQJtlp0NyRcw52Q5bKraLopqVifKXmqscJsedX81PGYR0IMuHuHIKkYsTCoDk\nrjhm3AZb7RDg2exTRYxeEFhztR6xwQ9GrTYXZJoVYp5lvWOqVpJytm3SSa7gpCG3\ng7R9L5PBAoGBAMzumodUf6IVfkak/oLyOJ56joiobTqdlcJD5oXzdq7U8552IOAK\n22j0JJLA01UQOHo61qxlBMqkoaSVj9veeaRtHZIcsRLTYBBSoiSSCnRvDFzickU/\no8Z9cbrg9Fbq6LQtZNvrM+auy4qjrFRCnMPs0tn8+ddFkAr2YjW7f9pVAoGBAMWG\nsPyj/3ehFWzteKHqGK/p4P2tpVZe7qXTvzNAmd6NGIMgsvqcfY8BbsyE/Yc3pAj7\nlQYp/huQC0GF5NMHMrNu6lqhsjb/8O2ptPyx6jzUOuKhpQENu3Q31DUQWMJSGEhU\nB5akqMlllGknpqF5164Ef+3D6QvadIes/X00kstNAoGBAKI27JLay/zczovU5rF4\nUmD/2ftKdsvDGVwgq0S0pulVH1H7Z6JwdaTqPFj90UqwAESgdnUXsWdGUb0Ztjnw\nLJF+3b1egLvKHWxOPJJ+F1B65mpPxOwTp+viODgZANAcOf8FP6Tk1Lxw+CTR0gMQ\nh05/E5gBqzI/mflTdgHaXSXRAoGAd/ALM7yY+JjVG6kuIJK2nspSlXaE+Gb4XbSv\nWn2VcK8X/TcztjyjeNwT3Re7oglFDzdEC9QfubjDPOwCP6kVPiLRJmscfYz3TDhJ\n705QvtLXVpl0Sal+81ibAAWG/6c9m116phwhaPjHHvq2kUIclkuhKkxVC5+ANonx\n+b6ci9kCgYEAn9ScPfhXC7q2rCVgYwNpzeL9bqAPM6CMXFU58Ypcs6ieJAwNSuqE\nFn2pPPKRRPIUVwhVfiXCmX6v63f2cr2yvSnoEtp1cJivKN8lw9fw4fMOIpXWVHZx\nvTwsjkrh8INWJnAY46VEi1YpIrFH25C/ynNSFFbKaJMJ6viiEP+BlZ8=\n-----END RSA PRIVATE KEY-----\n"
      AUTH_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnh9vfU9CB6xDJBYUc+5R\naCKdTiK0JKab/3CSgffzbfOFLTLlFpjdfL+9KQKUE+tvEL4MNW0CYeND25Gueycp\n7of2+Xn8ec2N6ah/EY4t+dUHeRS6LEUXVkOfQglL9hhVQG7N5lBFntlHxXnWOCli\n4arNpDdKMRVjy52G9aQbUIn3gx09Kglre0dS1M4LORXnlFReblFK0V342LuTD9oa\nmzpuJw4Gpj7WwXe+obLwDHIoBK1TBdJF+AQHPbaT8nAZBdAzOx8zTObd0bHfUuHb\nD8IzwY2V/OwPzNhJC2N8uznhJp8gBjqr206Y4D9Y3n62TqStk4gjNpMFBqmckBAS\nkQIDAQAB\n-----END PUBLIC KEY-----\n"
    networks:
      default:
        aliases:
          - flux-api.flux.local
    ports:
      - 3091:3000
    depends_on:
      - pg
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - cargo-home:/usr/local/cargo
      - rustup-home:/usr/local/rustup

  pg:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: flux
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.local/volumes/pg/data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d flux
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - flux-pg.flux.local

volumes:
  cargo-home:
  rustup-home:

networks:
  default:
    name: flux-dev
