services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    command: "cargo watch -x run"
    environment:
      APP_ADDR: 0.0.0.0:3000
      DATABASE_URL: postgres://postgres:postgres@flux-pg.flux.local/flux
      HISTFILE: /app/.local/.bash_history
    networks:
      default:
        aliases:
          - flux-api.flux.local
    ports:
      - 3091:3000
    depends_on:
      - pg
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - cargo-home:/usr/local/cargo
      - rustup-home:/usr/local/rustup

  pg:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: flux
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d flux
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - flux-pg.flux.local

  nats:
    image: nats:2
    ports:
      - 4222:4222
      - 8222:8222
    networks:
      default:
        aliases:
          - flux-nats.flux.local

  otel:
    image: otel/opentelemetry-collector-contrib
    command: "--config=/etc/otel-config.yaml"
    volumes:
      - ./.local/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - 4317:4317
    networks:
      default:
        aliases:
          - flux-newrelic.flux.local

volumes:
  cargo-home:
  rustup-home:
  pg-data:


networks:
  default:
    name: flux-dev
