name: CD

on:
  push:
    branches:
      - main

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          file: ./.github/workflows/Dockerfile
          push: true
          tags: bragovo/flux-api:latest
