name: CI

on: push

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --check

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo test
